/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoatButton: typeof import('@koihe/boat-ui/es')['BoatButton']
    BoatIcon: typeof import('@koihe/boat-ui/es')['BoatIcon']
    BoatNotification: typeof import('@koihe/boat-ui/es')['BoatNotification']
    BoatProgressNotification: typeof import('@koihe/boat-ui/es')['BoatProgressNotification']
  }
}
